"""Models updated for tracking number

Revision ID: 1c88d52782de
Revises: cdcca2ac4d59
Create Date: 2024-08-08 10:35:43.521360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c88d52782de'
down_revision = 'cdcca2ac4d59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_number', sa.String(length=32), nullable=True))
        batch_op.create_unique_constraint(None, ['tracking_number'])

    with op.batch_alter_table('recipient_addresses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipient_addresses_recipient_id_recipients', type_='foreignkey')
        batch_op.drop_column('recipient_id')

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.drop_constraint('fk_recipients_parcel_id_parcels', type_='foreignkey')
        batch_op.drop_column('parcel_id')

    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_addresses_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_user_addresses_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parcel_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_recipients_parcel_id_parcels', 'parcels', ['parcel_id'], ['id'])

    with op.batch_alter_table('recipient_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_recipient_addresses_recipient_id_recipients', 'recipients', ['recipient_id'], ['id'])

    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('tracking_number')

    # ### end Alembic commands ###
