"""Removes recipient unique email constraint

Revision ID: 4112ad7345f0
Revises: 197f727001a3
Create Date: 2024-08-13 19:37:57.657400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4112ad7345f0'
down_revision = '197f727001a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_index('ix_parcels_tracking_number')
        batch_op.create_index(batch_op.f('ix_parcels_tracking_number'), ['tracking_number'], unique=True)

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.drop_index('ix_recipients_email')
        batch_op.create_index(batch_op.f('ix_recipients_email'), ['email'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.create_index('ix_users_email', ['email'], unique=True)

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_recipients_email'))
        batch_op.create_index('ix_recipients_email', ['email'], unique=True)

    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_parcels_tracking_number'))
        batch_op.create_index('ix_parcels_tracking_number', ['tracking_number'], unique=True)

    # ### end Alembic commands ###
