"""Parcel cost billing user relationship

Revision ID: 5c7d0eda6e04
Revises: 8f53e22d79a2
Create Date: 2024-08-09 15:30:43.842086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c7d0eda6e04'
down_revision = '8f53e22d79a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
