"""Parcel cost and billing and user address relatoinship

Revision ID: 8f53e22d79a2
Revises: 5d7a285bef7b
Create Date: 2024-08-09 14:50:48.487853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f53e22d79a2'
down_revision = '5d7a285bef7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('cost')

    # ### end Alembic commands ###
