"""Adds updated column

Revision ID: a60afe30d5ed
Revises: 6b5445145176
Create Date: 2024-08-08 13:47:16.353042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a60afe30d5ed'
down_revision = '6b5445145176'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_addresses', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
