"""Recreate migrations to resolve issues

Revision ID: d6d77ad1801d
Revises: dce3a509cd9e
Create Date: 2024-08-09 23:40:28.000761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6d77ad1801d'
down_revision = 'dce3a509cd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_addresses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_billing_addresses_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('recipient_address_association', schema=None) as batch_op:
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.alter_column('recipient_full_name',
               existing_type=sa.VARCHAR(length=130),
               nullable=True)
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('user_address_association', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_address_association', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('recipients', schema=None) as batch_op:
        batch_op.alter_column('phone_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('recipient_full_name',
               existing_type=sa.VARCHAR(length=130),
               nullable=False)

    with op.batch_alter_table('recipient_address_association', schema=None) as batch_op:
        batch_op.alter_column('address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('recipient_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('billing_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_billing_addresses_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
